<!DOCTYPE html>
<html lang="en">
  <head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

  <title>How many profiles do Free users use?</title>
  <meta property="og:title" content="How many profiles do Free users use?" />
  <meta name="twitter:title" content="How many profiles do Free users use?" />
  <meta name="description" content="Not too many.">
  <meta property="og:description" content="Not too many.">
  <meta name="twitter:description" content="Not too many.">
  <meta name="author" content="Julian Winternheimer"/>
  <link href='https://jwinternheimer.github.io/img/favicon.ico' rel='icon' type='image/x-icon'/>
  <meta property="og:image" content="https://jwinternheimer.github.io/img/julian-avatar.png" />
  <meta name="twitter:image" content="https://jwinternheimer.github.io/img/julian-avatar.png" />
  <meta name="twitter:card" content="summary" />
  <meta name="twitter:site" content="@julheimer" />
  <meta name="twitter:creator" content="@julheimer" />
  <meta property="og:url" content="https://jwinternheimer.github.io/blog/profile_analysis/" />
  <meta property="og:type" content="website" />
  <meta property="og:site_name" content="Is That Your Analysis?" />

  <meta name="generator" content="Hugo 0.23" />
  <link rel="canonical" href="https://jwinternheimer.github.io/blog/profile_analysis/" />
  <link rel="alternate" href="https://jwinternheimer.github.io/index.xml" type="application/rss+xml" title="Is That Your Analysis?">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/katex.min.css" integrity="sha384-wITovz90syo1dJWVh32uuETPVEtGigN07tkttEqPv+uR2SE/mbQcG7ATL28aI9H0" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" href="https://jwinternheimer.github.io/css/main.css" />
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" />
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" />
  <link rel="stylesheet" href="https://jwinternheimer.github.io/css/pygment_highlights.css" />
  <link rel="stylesheet" href="https://jwinternheimer.github.io/css/highlight.min.css" />




<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/photoswipe.min.css" integrity="sha256-sCl5PUOGMLfFYctzDW3MtRib0ctyUvI9Qsmq2wXOeBY=" crossorigin="anonymous" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/default-skin/default-skin.min.css" integrity="sha256-BFeI1V+Vh1Rk37wswuOYn5lsTcaU96hGaI7OUVCLjPc=" crossorigin="anonymous" />



<div class="pswp" tabindex="-1" role="dialog" aria-hidden="true">

<div class="pswp__bg"></div>

<div class="pswp__scroll-wrap">
    
    <div class="pswp__container">
      <div class="pswp__item"></div>
      <div class="pswp__item"></div>
      <div class="pswp__item"></div>
    </div>
    
    <div class="pswp__ui pswp__ui--hidden">
    <div class="pswp__top-bar">
      
      <div class="pswp__counter"></div>
      <button class="pswp__button pswp__button--close" title="Close (Esc)"></button>
      <button class="pswp__button pswp__button--share" title="Share"></button>
      <button class="pswp__button pswp__button--fs" title="Toggle fullscreen"></button>
      <button class="pswp__button pswp__button--zoom" title="Zoom in/out"></button>
      
      
      <div class="pswp__preloader">
        <div class="pswp__preloader__icn">
          <div class="pswp__preloader__cut">
            <div class="pswp__preloader__donut"></div>
          </div>
        </div>
      </div>
    </div>
    <div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap">
      <div class="pswp__share-tooltip"></div>
    </div>
    <button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)">
    </button>
    <button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)">
    </button>
    <div class="pswp__caption">
      <div class="pswp__caption__center"></div>
    </div>
    </div>
    </div>
</div>

</head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top navbar-custom">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="https://jwinternheimer.github.io">Is That Your Analysis?</a>
    </div>

    <div class="collapse navbar-collapse" id="main-navbar">
      <ul class="nav navbar-nav navbar-right">
        
          
            <li>
              <a title="Blog" href="/">Blog</a>
            </li>
          
        
          
            <li class="navlinks-container">
              <a class="navlinks-parent" href="javascript:void(0)">Samples</a>
              <div class="navlinks-children">
                
                  <a href="/post/2017-03-07-bigimg-sample">Big Image Sample</a>
                
                  <a href="/post/2017-03-05-math-sample">Math Sample</a>
                
              </div>
            </li>
          
        
          
            <li>
              <a title="About" href="/page/about/">About</a>
            </li>
          
        
          
            <li>
              <a title="Tags" href="/tags">Tags</a>
            </li>
          
        

        

        
      </ul>
    </div>

    <div class="avatar-container">
      <div class="avatar-img-border">
        
          <a title="Is That Your Analysis?" href="https://jwinternheimer.github.io">
            <img class="avatar-img" src="https://jwinternheimer.github.io/img/julian-avatar.png" alt="Is That Your Analysis?" />
          </a>
        
      </div>
    </div>

  </div>
</nav>




    
  
  
  




  
    <div id="header-big-imgs" data-num-img=1 data-img-src-1="https://jwinternheimer.github.io/blog/profile_analysis_files/figure-html/unnamed-chunk-10-1.png" ></div>
  

  <header class="header-section has-img">
    
      <div class="intro-header big-img">
        
        <div class="container">
          <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
              <div class="post-heading">
                <h1>How many profiles do Free users use?</h1>
                  
                    
                      <h2 class="post-subheading">Not too many.</h2>
                    
                  
                  
                    <span class="post-meta">
  Posted on June 21, 2017
  
</span>


                  
              </div>
            </div>
          </div>
        </div>
        <span class="img-desc" style="display: inline;"></span>
      </div>
    
    <div class="intro-header no-img">
      
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <div class="post-heading">
              <h1>How many profiles do Free users use?</h1>
                
                  
                    <h2 class="post-subheading">Not too many.</h2>
                  
                
                
                  <span class="post-meta">
  Posted on June 21, 2017
  
</span>


                
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>


    
<div class="container" role="main">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
      <article role="main" class="blog-post">
        <div id="introduction" class="section level2">
<h2>Introduction</h2>
<p>There is a big focus on simplifying the product for Buffer users on free plans in 2017 in order to create a more intuitive experience and encourage more upgrades.</p>
<p>The purpose of this analysis is to get a better understanding of how users currently interact with the free plan, in order to better inform decisions around future plan limits. Specifically, we would love to learn about how many profiles users connect and actually schedule updates for.</p>
<p>More data questions and context can be found in <a href="https://paper.dropbox.com/doc/Free-Plan-data-KJNJLDW3KtfMdZK4Z6DRS"><strong>this Paper</strong></a>, and potential changes to the Free plan can be found in <a href="https://paper.dropbox.com/doc/Free-plan-changes-DVheYkvNs3yiE9Nhb9XRF"><strong>this Paper</strong></a>.</p>
</div>
<div id="methodology" class="section level2">
<h2>Methodology</h2>
<p>To answer this question, we’d like to only consider users that are currently <em>active</em>, and analyze their usage <em>during the period in which they were active in Buffer</em>. In this case, <em>active</em> is defined as having scheduled at least one update with Buffer in the previous 28 days.</p>
<p>We’ll gather all of the currently active users that are on free plans. Then, we will gather data on the number of profiles they have connected and the number of updates that they have scheduled <em>for each profile</em>.</p>
<p>Once we have this data, we will gather some summary statistics on the number of active profiles for each active user, and visualize the distribution of the number of profiles in use. It is unlikely to be normally distributed (bell shaped), so visualizing this breakdown would be useful to understanding the potential impact that changing the limits might have.</p>
</div>
<div id="data-collection" class="section level2">
<h2>Data collection</h2>
<p>Let’s start by getting the Free users that have scheduled at least one update in the past 28 days. We’ll use the following SQL query to grab them.</p>
<pre class="sql"><code>with user_facts as (
  select
    up.user_id
    , max(up.created_at) as last_update_created_at
  from transformed_updates as up
  inner join users
    on users.user_id = up.user_id
  where up.status != &#39;service&#39;
  and users.billing_plan = &#39;individual&#39;
  group by up.user_id
)
select
  user_id
  , last_update_created_at
from user_facts
where last_update_created_at &gt; (current_date - 29)</code></pre>
<p>There are around 250 thousand users in this dataset! Now we need to get the number of updates they have scheduled, and the number of profiles that they have scheduled updates for.</p>
<pre class="sql"><code>select
  up.user_id
  , count(distinct up.id) as updates_count
  , count(distinct up.profile_id) as profile_count
from transformed_updates as up
left join users
  on up.user_id = users.user_id
where users.billing_plan = &#39;individual&#39;
and up.status != &#39;service&#39;
and up.created_at &gt; (current_date - 29)
group by up.user_id</code></pre>
<p>Awesome! Now let’s join the <code>updates</code> and <code>users</code> dataframes so that we’ll have the number of updates and active profiles for each user. We’ll use <code>dplyr</code>’s <code>left_join</code> function and replace <code>NA</code> values with 0.</p>
<pre class="r"><code># Join updates and users
users &lt;- users %&gt;%
  left_join(updates, by = &#39;user_id&#39;)

# Replace NAs with 0s
users[is.na(users)] &lt;- 0</code></pre>
</div>
<div id="exploratory-analysis" class="section level2">
<h2>Exploratory analysis</h2>
<p>Now that we have the updates and profile counts for each active user, we can compute some quick summary statistics for our population.</p>
<pre class="r"><code># Get summary stats on the number of profiles
summary(users$profile_count)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   1.000   1.000   1.000   1.877   2.000 194.000</code></pre>
<p>Here is the breakdown:</p>
<ul>
<li>Around 50% of active Free plan users scheduled updates for only 1 profile in the past 28 days.</li>
<li>The average number of profiles that active Free plan users used in the past 28 days is 1.88.</li>
<li>Around 75% of active Free plan users scheduled updates for only 2 or less profiles.</li>
<li>Someone scheduled updates for 194 profiles in the past 28 days!</li>
</ul>
<p>The maximum of 194 brings up a good point about our sample: these are only users that are <em>currently</em> on individual plans. This means that they could have been on a paid plan in the past 28 days. I don’t think it’s a huge portion, or very significant for this particular analysis, but it’s something to keep in mind!</p>
<p>Let’s look at the distribution.</p>
<p><img src="/blog/profile_analysis_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>Wow, that’s interesting! It looks like most currently active Free users have only scheduled updates to one profile in the past 28 days. Let’s look at the CDF of this distribution.</p>
<p><img src="/blog/profile_analysis_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>Interesting! This graph tells us the following:</p>
<ul>
<li>Around 56% of users scheduled updates to 1 profile in the past 28 days.</li>
<li>Around 76% of users scheduled updates to 2 or less profiles in the past 28 days.</li>
<li>Around 91% of users scheduled updates to 3 or less profiles in the past 28 days.</li>
<li>Around 98% of users scheduled updates to 4 or less profiles in the past 28 days.</li>
</ul>
</div>
<div id="conclusions" class="section level2">
<h2>Conclusions</h2>
<p>If we were to go with the “less limited” Free plan and only allow users to connect up to 3 profiles, the data suggests that somewhere around 10% of currently active users would be affected. This equates to around 25k users.</p>
<p>If we were to go with the “more limited” Free plan and only allow 2 profiles, the data suggests that somewhere around 25% of currently active users would be affected! This equates to around 63k users.</p>
<p>I think it’s important to note that this is just a snapshot of <em>currently</em> active users that are <em>currently</em> on Individual plans, but I do think we can infer some insights from them!</p>
</div>

      </article>

      <ul class="pager blog-pager">
        
        
          <li class="next">
            <a href="https://jwinternheimer.github.io/blog/updates_per_day/" data-toggle="tooltip" data-placement="top" title="Free Plan: Updates Per Day">Next Post &rarr;</a>
          </li>
        
      </ul>

      
        
      

    </div>
  </div>
</div>

    <footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <ul class="list-inline text-center footer-links">
          
              <li>
                <a href="mailto:julianwinternheimer@gmail.com" title="Email me">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-envelope fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li>
                <a href="https://www.facebook.com/julian.winternheimer" title="Facebook">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li>
                <a href="https://github.com/jwinternheimer" title="GitHub">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li>
                <a href="https://twitter.com/julheimer" title="Twitter">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li>
                <a href="https://linkedin.com/in/jwinternheimer" title="LinkedIn">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-linkedin fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
          
          <li>
            <a href="https://jwinternheimer.github.io/index.xml" title="RSS">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-rss fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
          
        </ul>
        <p class="credits copyright text-muted">
          Julian Winternheimer
          &nbsp;&bull;&nbsp;
          2017

          
            &nbsp;&bull;&nbsp;
            <a href="https://jwinternheimer.github.io">Is That Your Analysis?</a>
          
        </p>
        
        <p class="credits theme-by text-muted">
          <a href="http://gohugo.io">Hugo v0.23</a> powered &nbsp;&bull;&nbsp; Theme by <a href="http://deanattali.com/beautiful-jekyll/">Beautiful Jekyll</a> adapted to <a href="https://github.com/halogenica/beautifulhugo">Beautiful Hugo</a>
          
        </p>
      </div>
    </div>
  </div>
</footer>

<script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/katex.min.js" integrity="sha384-/y1Nn9+QQAipbNQWU65krzJralCnuOasHncUFXGkdwntGeSvQicrYkiUBwsgUqc1" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/contrib/auto-render.min.js" integrity="sha384-dq1/gEHSxPZQ7DdrM82ID4YVol9BYyU7GbWlIwnwyPzotpoc57wDw/guX8EaYGPx" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="https://jwinternheimer.github.io/js/main.js"></script>
<script src="https://jwinternheimer.github.io/js/highlight.min.js"></script>
<script> hljs.initHighlightingOnLoad(); </script>
<script> renderMathInElement(document.body); </script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/photoswipe.min.js" integrity="sha256-UplRCs9v4KXVJvVY+p+RSo5Q4ilAUXh7kpjyIP5odyc=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/photoswipe-ui-default.min.js" integrity="sha256-PWHOlUzc96pMc8ThwRIXPn8yH4NOLu42RQ0b9SpnpFk=" crossorigin="anonymous"></script>
<script src="/js/load-photoswipe.js"></script>




  </body>
</html>

