<!DOCTYPE html>
<html lang="en">
  <head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

  <title>Equal Pay Report 2018</title>
  <meta property="og:title" content="Equal Pay Report 2018" />
  <meta name="twitter:title" content="Equal Pay Report 2018" />
  <meta name="description" content="What Men and Women Earn at Buffer">
  <meta property="og:description" content="What Men and Women Earn at Buffer">
  <meta name="twitter:description" content="What Men and Women Earn at Buffer">
  <meta name="author" content="Julian Winternheimer"/>
  <link href='/img/favicon.ico' rel='icon' type='image/x-icon'/>
  <meta property="og:image" content="/img/julian-avatar.png" />
  <meta name="twitter:image" content="/img/julian-avatar.png" />
  <meta name="twitter:card" content="summary" />
  <meta name="twitter:site" content="@julheimer" />
  <meta name="twitter:creator" content="@julheimer" />
  <meta property="og:url" content="/blog/equal-pay-2018/" />
  <meta property="og:type" content="website" />
  <meta property="og:site_name" content="Data Analysis?" />

  <meta name="generator" content="Hugo 0.23" />
  <link rel="canonical" href="/blog/equal-pay-2018/" />
  <link rel="alternate" href="/index.xml" type="application/rss+xml" title="Data Analysis?">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/katex.min.css" integrity="sha384-wITovz90syo1dJWVh32uuETPVEtGigN07tkttEqPv+uR2SE/mbQcG7ATL28aI9H0" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" href="/css/main.css" />
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" />
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" />
  <link rel="stylesheet" href="/css/pygment_highlights.css" />
  <link rel="stylesheet" href="/css/highlight.min.css" />




<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/photoswipe.min.css" integrity="sha256-sCl5PUOGMLfFYctzDW3MtRib0ctyUvI9Qsmq2wXOeBY=" crossorigin="anonymous" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/default-skin/default-skin.min.css" integrity="sha256-BFeI1V+Vh1Rk37wswuOYn5lsTcaU96hGaI7OUVCLjPc=" crossorigin="anonymous" />



<div class="pswp" tabindex="-1" role="dialog" aria-hidden="true">

<div class="pswp__bg"></div>

<div class="pswp__scroll-wrap">
    
    <div class="pswp__container">
      <div class="pswp__item"></div>
      <div class="pswp__item"></div>
      <div class="pswp__item"></div>
    </div>
    
    <div class="pswp__ui pswp__ui--hidden">
    <div class="pswp__top-bar">
      
      <div class="pswp__counter"></div>
      <button class="pswp__button pswp__button--close" title="Close (Esc)"></button>
      <button class="pswp__button pswp__button--share" title="Share"></button>
      <button class="pswp__button pswp__button--fs" title="Toggle fullscreen"></button>
      <button class="pswp__button pswp__button--zoom" title="Zoom in/out"></button>
      
      
      <div class="pswp__preloader">
        <div class="pswp__preloader__icn">
          <div class="pswp__preloader__cut">
            <div class="pswp__preloader__donut"></div>
          </div>
        </div>
      </div>
    </div>
    <div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap">
      <div class="pswp__share-tooltip"></div>
    </div>
    <button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)">
    </button>
    <button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)">
    </button>
    <div class="pswp__caption">
      <div class="pswp__caption__center"></div>
    </div>
    </div>
    </div>
</div>

</head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top navbar-custom">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Data Analysis?</a>
    </div>

    <div class="collapse navbar-collapse" id="main-navbar">
      <ul class="nav navbar-nav navbar-right">
        
          
            <li>
              <a title="Blog" href="/">Blog</a>
            </li>
          
        
          
            <li class="navlinks-container">
              <a class="navlinks-parent" href="javascript:void(0)">Samples</a>
              <div class="navlinks-children">
                
                  <a href="/post/2017-03-07-bigimg-sample">Big Image Sample</a>
                
                  <a href="/post/2017-03-05-math-sample">Math Sample</a>
                
              </div>
            </li>
          
        
          
            <li>
              <a title="About" href="/page/about/">About</a>
            </li>
          
        
          
            <li>
              <a title="Tags" href="/tags">Tags</a>
            </li>
          
        

        

        
      </ul>
    </div>

    <div class="avatar-container">
      <div class="avatar-img-border">
        
          <a title="Data Analysis?" href="/">
            <img class="avatar-img" src="/img/julian-avatar.png" alt="Data Analysis?" />
          </a>
        
      </div>
    </div>

  </div>
</nav>




    
  
  
  




  

  <header class="header-section ">
    
    <div class="intro-header no-img">
      
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <div class="post-heading">
              <h1>Equal Pay Report 2018</h1>
                
                  
                    <h2 class="post-subheading">What Men and Women Earn at Buffer</h2>
                  
                
                
                  <span class="post-meta">
  Posted on March 12, 2018
  
</span>


                
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>


    
<div class="container" role="main">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
      <article role="main" class="blog-post">
        <p>Last April we released Buffer’s first <a href="https://open.buffer.com/equal-pay/">equal pay report</a> in celebration of Equal Pay Day. Since then, we have <a href="https://open.buffer.com/salary-formula/">overhauled our salary formula</a> and made many internal role changes. Given all of these changes, I’m excited to dig into our salary data today and see how we’re doing.</p>
<div id="data-collection" class="section level3">
<h3>Data Collection</h3>
<p>The data we’ll use in this analysis comes from <a href="https://docs.google.com/spreadsheets/d/1cRI2VUhFVWB-c8wTmTnbT2OMOdDNnbh06bjCID_IKt0/edit?usp=sharing">this spreadsheet</a>. We’ll simply read in a CSV downloaded from this sheet.</p>
<pre class="r"><code># read csv
salaries &lt;- read.csv(&quot;~/Downloads/salaries.csv&quot;, header = TRUE)</code></pre>
<p>Now we’re ready for some exploratory analysis.</p>
</div>
<div id="global-summary-statistics" class="section level3">
<h3>Global Summary Statistics</h3>
<p>Let’s begin by describing the distribution of salaries for all team members of Buffer. It might be helpful to define a couple fields in our dataset. The <code>salary</code> field contains the totol pre-tax salaries of team members before tax in US dollars. This includes dependent grants and the choice to receive a higher salary instead of stock options.</p>
<p>The <code>base_salary</code> field contains the base salary as calculated by our new salary formula. This <em>excludes</em> dependent grants and salary choices.</p>
<p>In this analysis I chose to focus on the <code>salary</code> values, because that is what people take home (for the most part).</p>
<pre class="r"><code># summarise salary
summary(salaries$salary)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   69483   86864  109350  114211  128412  265315</code></pre>
<p>The median salary at Buffer is $109K and the average is $114K. We can plot the distribution of salaries across Buffer.</p>
<pre class="r"><code># define cuts
cuts &lt;- seq(60000, 280000, 20000)

# define salary buckets
salaries &lt;- salaries %&gt;% 
  mutate(salary_bin = cut(salary, breaks = cuts, dig.lab = 10))

# plot distribution of salaries
salaries %&gt;% 
  count(salary_bin) %&gt;% 
  ggplot(aes(x = salary_bin, y = n)) +
  geom_bar(stat = &#39;identity&#39;) +
  theme_ipsum() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x = NULL, y = &quot;Team Members&quot;, title = &quot;Salary Distribution&quot;)</code></pre>
<p><img src="/blog/equal-pay-2018_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>The most common salary “bin” is 80-100K. Let’s break salary down by gender now.</p>
</div>
<div id="average-salary-by-gender" class="section level3">
<h3>Average Salary by Gender</h3>
<p>We can quickly calculate the average and median salaries for both men and women at Buffer.</p>
<pre class="r"><code># calculate average and median salaries
salaries %&gt;% 
  group_by(gender) %&gt;% 
  summarise(average_salary = mean(salary), median_salary = median(salary))</code></pre>
<pre><code>## # A tibble: 2 x 3
##   gender average_salary median_salary
##   &lt;fct&gt;           &lt;dbl&gt;         &lt;dbl&gt;
## 1 female         106819         94546
## 2 male           117530        114215</code></pre>
<p>The average salary for females at Buffer is <strong>$106,808</strong> and the median is <strong>$94,546</strong>. The average salary for men is <strong>$117,530</strong> and the median is <strong>$114,215</strong>.</p>
<p>If we look at averages, men earn around 10% more than women – if we look at medians, men earn around 21% more than women!</p>
<p><img src="/blog/equal-pay-2018_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p><img src="/blog/equal-pay-2018_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>This discrpency can be surprising, especially for a company with a salary formula! Gender does not enter the salary formula in any way. However, there is something interesting going on - let’s take a closer look at the data.</p>
</div>
<div id="technical-and-non-technical-roles" class="section level3">
<h3>Technical and Non-Technical Roles</h3>
<p>I’m not the biggest fan of this terminology, but it can be useful to describe roles. Technical roles include engineering, data, design, product, and our full-stack marketer. Non-technical roles include marketing, leadership, and advocacy.</p>
<p>If we calculate the average salaries for technical and non-technical roles, we might see something interesting.</p>
<pre class="r"><code># calculate average salaries for tech and non-tech roles
salaries %&gt;% 
  group_by(role_type, gender) %&gt;% 
  summarise(average_salary = mean(salary))</code></pre>
<pre><code>## # A tibble: 4 x 3
## # Groups:   role_type [?]
##   role_type     gender average_salary
##   &lt;fct&gt;         &lt;fct&gt;           &lt;dbl&gt;
## 1 non-technical female         105587
## 2 non-technical male           104171
## 3 technical     female         112363
## 4 technical     male           125287</code></pre>
<p>This is interesting. If we segment team members by their role type, we can see that women earn around 1% more than men in non-technical roles, and men earn around only 12% more than women in technical roles.</p>
<p>This seems to explain the overall difference in average salaries. There are more men in technical roles, which tend to demand higher salaries. That, coupled with the fact that men earn more on-average than women in technical roles, leads to the 10% difference in the overall average salary.</p>
<p><img src="/blog/equal-pay-2018_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p><img src="/blog/equal-pay-2018_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
</div>
<div id="salaries-by-team" class="section level3">
<h3>Salaries by Team</h3>
<p>We can also plot the average salary for each team at Buffer.</p>
<p><img src="/blog/equal-pay-2018_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<pre class="r"><code>salaries %&gt;%
  group_by(team) %&gt;%
  summarise(average_salary = mean(salary)) %&gt;% 
  arrange(desc(average_salary))</code></pre>
<pre><code>## # A tibble: 9 x 2
##   team        average_salary
##   &lt;fct&gt;                &lt;dbl&gt;
## 1 leadership          169675
## 2 engineering         127177
## 3 product             124146
## 4 data                121996
## 5 design              113257
## 6 finance             103073
## 7 people               99498
## 8 marketing            86506
## 9 advocacy             83751</code></pre>
<p>Interesting stuff overall!</p>
</div>

      </article>

      <ul class="pager blog-pager">
        
          <li class="previous">
            <a href="/blog/text-features/" data-toggle="tooltip" data-placement="top" title="Analyzing Tweets with TextFeatures">&larr; Previous Post</a>
          </li>
        
        
      </ul>

      
        
      

    </div>
  </div>
</div>

    <footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <ul class="list-inline text-center footer-links">
          
              <li>
                <a href="mailto:julianwinternheimer@gmail.com" title="Email me">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-envelope fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li>
                <a href="https://www.facebook.com/julian.winternheimer" title="Facebook">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li>
                <a href="https://github.com/jwinternheimer" title="GitHub">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li>
                <a href="https://twitter.com/julheimer" title="Twitter">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li>
                <a href="https://linkedin.com/in/jwinternheimer" title="LinkedIn">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-linkedin fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
          
          <li>
            <a href="/index.xml" title="RSS">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-rss fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
          
        </ul>
        <p class="credits copyright text-muted">
          Julian Winternheimer
          &nbsp;&bull;&nbsp;
          2018

          
            &nbsp;&bull;&nbsp;
            <a href="/">Data Analysis?</a>
          
        </p>
        
        <p class="credits theme-by text-muted">
          <a href="http://gohugo.io">Hugo v0.23</a> powered &nbsp;&bull;&nbsp; Theme by <a href="http://deanattali.com/beautiful-jekyll/">Beautiful Jekyll</a> adapted to <a href="https://github.com/halogenica/beautifulhugo">Beautiful Hugo</a>
          
        </p>
      </div>
    </div>
  </div>
</footer>

<script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/katex.min.js" integrity="sha384-/y1Nn9+QQAipbNQWU65krzJralCnuOasHncUFXGkdwntGeSvQicrYkiUBwsgUqc1" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/contrib/auto-render.min.js" integrity="sha384-dq1/gEHSxPZQ7DdrM82ID4YVol9BYyU7GbWlIwnwyPzotpoc57wDw/guX8EaYGPx" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="/js/main.js"></script>
<script src="/js/highlight.min.js"></script>
<script> hljs.initHighlightingOnLoad(); </script>
<script> renderMathInElement(document.body); </script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/photoswipe.min.js" integrity="sha256-UplRCs9v4KXVJvVY+p+RSo5Q4ilAUXh7kpjyIP5odyc=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/photoswipe-ui-default.min.js" integrity="sha256-PWHOlUzc96pMc8ThwRIXPn8yH4NOLu42RQ0b9SpnpFk=" crossorigin="anonymous"></script>
<script src="/js/load-photoswipe.js"></script>




  </body>
</html>

